export enum AttributeNames {
  If = 'if',
  LargerThan = '>',
  SmallerThan = '<',
  Equal = '=',
  NotEqual = '!=',
  Multiply = '*',
  Division = '/',
  Addition = '+',
  Subtraction = '-',
  Power = '^',
  InputNumber = 'I',
  BooleanMethod = 'Mb',
  FloatMethod = 'Mf',
  InputFields = 'Input Fields',
  StaticValue = 'Static Value',
  InputValue = 'Input Value',
  InputName = 'Input Name',
  InputReference = 'Input Reference',
  NumericArray = 'Numeric Array',
  Function = 'Function',
  Version = 'Version',
  NumericInputs = 'Numeric Inputs',
  NumericInputVariable = 'Variable',
  NumericInputValue = 'Value',
  NumericInputName = 'Name',
  NumericScientificSymbol = 'Symbol',
  NumericScientificSubscript = 'Subscript',
  Character = 'c',
}
