export const ROOT_NODE_NAME = 'ROOT_NODE';
export const INITIAL_INPUT_VIEW_STRING =
  'ABJQAoAfSCcQ-hIDYAUAPpBOIfQkCEAKAH0gnEPoSAoAKYCECEAEUBCFEACkAhAiAAARgwIMICRUACICI';
export const MIN_DESKTOP_WIDTH = 800;
